name: Trigger auto deployment for angular

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - "**"
      - ".github/workflows/angular-AutoDeployTrigger-f724e108-5aaf-49e6-a13e-296a2c466136.yml"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Inject Google Client ID into environment.prod.ts
        run: |
          echo "Updating environment.prod.ts with secret GOOGLE_CLIENT_ID"
          sed -i \
            "s|googleClientId: '.*'|googleClientId: '${{ secrets.GOOGLE_CLIENT_ID }}'|g" \
            src/environments/environment.prod.ts

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ANGULAR_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ANGULAR_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ANGULAR_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: acrdvfvluycp45lo.azurecr.io
          registryUsername: ${{ secrets.ANGULAR_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ANGULAR_REGISTRY_PASSWORD }}
          containerAppName: angular
          resourceGroup: rg-adjutum
          imageToBuild: acrdvfvluycp45lo.azurecr.io/angular:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_
